// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFMjci49RQ1AyU46HyA0Sk2gtYMTgwL8',
    appId: '1:879959483672:web:a8a2832c8c0ac5ab1dea6d',
    messagingSenderId: '879959483672',
    projectId: 'imagedata-c3fd3',
    authDomain: 'imagedata-c3fd3.firebaseapp.com',
    storageBucket: 'imagedata-c3fd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdg1-3TNXC3fYO9QxHbtmTCMTAjJX9NX8',
    appId: '1:879959483672:android:aa34fd08e22de9c91dea6d',
    messagingSenderId: '879959483672',
    projectId: 'imagedata-c3fd3',
    storageBucket: 'imagedata-c3fd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDN8MaG1hCPNUVI4siIGH_kDWF935dNg',
    appId: '1:879959483672:ios:c1af86d60d1fa5ec1dea6d',
    messagingSenderId: '879959483672',
    projectId: 'imagedata-c3fd3',
    storageBucket: 'imagedata-c3fd3.firebasestorage.app',
    iosBundleId: 'com.example.imageoedit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSDN8MaG1hCPNUVI4siIGH_kDWF935dNg',
    appId: '1:879959483672:ios:c1af86d60d1fa5ec1dea6d',
    messagingSenderId: '879959483672',
    projectId: 'imagedata-c3fd3',
    storageBucket: 'imagedata-c3fd3.firebasestorage.app',
    iosBundleId: 'com.example.imageoedit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiFMjci49RQ1AyU46HyA0Sk2gtYMTgwL8',
    appId: '1:879959483672:web:60bf970d564c71df1dea6d',
    messagingSenderId: '879959483672',
    projectId: 'imagedata-c3fd3',
    authDomain: 'imagedata-c3fd3.firebaseapp.com',
    storageBucket: 'imagedata-c3fd3.firebasestorage.app',
  );
}
